"""Add alert table

Revision ID: 0627579a2536
Revises: 0a00177758d2
Create Date: 2025-07-09 12:20:28.583174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0627579a2536'
down_revision = '0a00177758d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('target_price', sa.Float(), nullable=False),
    sa.Column('condition', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_user_id'))
        batch_op.drop_index(batch_op.f('ix_alert_symbol'))
        batch_op.drop_index(batch_op.f('ix_alert_is_active'))

    op.drop_table('alert')
    # ### end Alembic commands ###
