"""Add nullable pnl column to trade table

Revision ID: 0a00177758d2
Revises: fb930badd88d
Create Date: 2025-07-08 23:52:47.380387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a00177758d2'
down_revision = 'fb930badd88d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pnl', sa.Float(), nullable=True))
        batch_op.alter_column('setup_reason',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_column('trade_type')
        batch_op.drop_column('price')
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('trade_type', sa.VARCHAR(length=4), autoincrement=False, nullable=False))
        batch_op.alter_column('setup_reason',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('pnl')

    # ### end Alembic commands ###
