"""Add free_searches_remaining to User model

Revision ID: 299771da5831
Revises: 38b52519afad
Create Date: 2025-08-12 17:14:31.326546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '299771da5831'
down_revision = '38b52519afad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('free_searches_remaining', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('free_searches_remaining')

    # ### end Alembic commands ###
