"""Add watchlist_item table

Revision ID: 40f597c3aa61
Revises: e021b3ff0550
Create Date: 2025-05-01 11:40:59.373276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40f597c3aa61'
down_revision = 'e021b3ff0550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'symbol', name='uq_user_symbol')
    )
    with op.batch_alter_table('watchlist_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlist_item_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_watchlist_item_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlist_item_user_id'))
        batch_op.drop_index(batch_op.f('ix_watchlist_item_symbol'))

    op.drop_table('watchlist_item')
    # ### end Alembic commands ###
