"""Add holding table for portfolio tracking

Revision ID: 6d0f1688ae03
Revises: 40f597c3aa61
Create Date: 2025-05-09 09:43:06.568688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d0f1688ae03'
down_revision = '40f597c3aa61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('purchase_price', sa.Float(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('holding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holding_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_holding_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holding_user_id'))
        batch_op.drop_index(batch_op.f('ix_holding_symbol'))

    op.drop_table('holding')
    # ### end Alembic commands ###
