"""Add asset class and setup reason to Trade model

Revision ID: fb930badd88d
Revises: 4f68f3a3eae3
Create Date: 2025-07-08 19:23:18.040466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb930badd88d'
down_revision = '4f68f3a3eae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_class', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('setup_reason', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.drop_column('setup_reason')
        batch_op.drop_column('asset_class')

    # ### end Alembic commands ###
